### ISSUE TITLE
Baseimage 0.9.19: Upgrade OpenSSL to 1.0.2x builds

### ISSUE THREAD

**Issue by rix1337** [aptalca/docker-webserver#16]
Refering to:
https://www.nginx.com/blog/supporting-http2-google-chrome-users/

We currently cannot offer HTTP v2 (which is a major speed improvement over 1.1) through OpenSSL v1.0.1

could you upgrade to another baseimage that has built in openssl 1.0.2 (ubuntu 16.04) or build the latest openssl into this image?

**Comment by rix1337** [comment]
Actually baseimage 0.9.19 should do!

**Comment by aptalca** [comment]
Replied to PR
