### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by patriknyblad** [aptalca/docker-webserver#18]
I might not understand it fully but I can not configure multiple domains. The reason I want to do so is that I have nginx as my front and reverse proxy to other virtual machines on my unRaid system. These different machines might be related to different domains.

**Comment by aptalca** [comment]
Multiple domains are not supported with this container (only multiple subdomains with the same domain are allowed). I thought about it but couldn't find an easy way that would not break the automation of letsencrypt.

I suggest using a plain nginx container and setting up letsencrypt yourself manually.

**Comment by patriknyblad** [comment]
Thanks for the quick response 👍 

I would like the same certificate to be valid for multiple domains as well as subdomains. I don't specifically need multiple certificates. Think of it like Google's SSL cert, it contains both google.com and android.com (among others). That should be possible with `certbot` by passing multiple `-d` arguments just like with subdomains.

I'm very new to this (just started with it two days ago) but would like to help out if possible. If multiple domains are not possible using `certbot` or `letsencrypt` then I guess we are screwed.

**Comment by aptalca** [comment]
It is possible with letsencrypt, you can add as many domains as you like. 

But it's not currently possible with this specific container because it would break the automation revolving around nginx settings and cert location, etc.
