### ISSUE TITLE
PHP blank page

### ISSUE THREAD

**Issue by rix1337** [aptalca/docker-webserver#4]
This far certificate renewal works well (for admin.mysite.foo and mysite.foo)
and my pages (including reverse proxies) are functioning also.

Fail2ban is working flawlessly.

What I fail to achieve is getting PHP to output anything.

Using the config from the `default` site will output only a blank response (=white page).

I have commented the `:9000` line and tried the fpm one below but neither work..

Any idea how to properly enable PHP?

Thank you!

**Comment by rix1337** [comment]
Update: less urgent for me personally. I have "ripped" the html code from muximux, so it runs without php, which was the reason for this request. Leaving it open though, if someone else is interested.

**Comment by aptalca** [comment]
Finally figured out the bug. Will be fixed in the next update

**Comment by aptalca** [comment]
Update pushed

**Comment by rix1337** [comment]
Heroic effort. Thank you!
